---
dist: trusty
language: node_js

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo $HOME && echo $PATH

install:
  - yarn install --pure-lockfile
  - rm node_modules/ember-cli/blueprints/module-unification-app/files/src/ui/routes/application/template.hbs
  - cp node_modules/handlebars/dist/handlebars.js node_modules/handlebars/handlebars.js

script:
  - pwd
  - yarn test
  - ember build
